# Use the official Python base image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements.txt file to the container
COPY requirements.txt .

# Install the required packages
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code to the container
COPY . .

# Expose the port on which the Streamlit app will run
EXPOSE 8080

# Set the command to run the Streamlit app when the container starts
CMD ["streamlit", "run", "--server.port", "8080", "main.py"]